<a href="https://colab.research.google.com/github/muhdadil-a11y/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python

#array : collection of data with same datatype(Homogenious)

a=np.array([1,2,3.0,4,"a"])
print(a)

['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing : forward slicing backward slicing
b=np.array([1,2,3,4,5])

print(b[0:2])
print(b[-1:-3:-1])
print(b[3:5])
print(b[-4:-6:-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension
import numpy as np
a=np.array([0,1,2,3,4])
b=np.array([[1,2],[3,4]])
a.ndim #dimention=1 vector
b.ndim #dimention=2 matrix
print(b)
b.shape

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
#create a 2x2 matrix 2,3,4,5

z=np.array([[2,1],[4,5]])
print(z)
print(z.shape)
print(z.ndim)
print(z.size)

[[2 1]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix and print,size,shape,diamention

q=np.array([[2,5,7],[1,6,3]])
print(q)
print(q.shape)
print(q.size)
print(q.ndim)

[[2 5 7]
 [1 6 3]]
(2, 3)
6
2


In [ ]:
#create a 4x2 matric and print size shape diamention
q=np.array([[2,5],[1,6],[2,5],[5,9]])
print(q)
print(q.shape)
print(q.size)
print(q.ndim)

[[2 5]
 [1 6]
 [2 5]
 [5 9]]
(4, 2)
8
2


In [ ]:
#create a 4x4 matrix
q=np.array([[2,5,7,4],[1,6,3,4],[2,1,6,3],[7,8,3,2]])
print(q)
print(q.shape)
print(q.size)
print(q.ndim)

[[2 5 7 4]
 [1 6 3 4]
 [2 1 6 3]
 [7 8 3 2]]
(4, 4)
16
2


In [ ]:
import numpy as np
q=np.array([[2,5,7,4],[1,6,3,4],[2,1,6,3],[7,8,3,2]])
print(q)
print(q.shape)
print(q.size)
print(q.ndim)
print(q[2:,1:3])
print(q[:3,2:])

[[2 5 7 4]
 [1 6 3 4]
 [2 1 6 3]
 [7 8 3 2]]
(4, 4)
16
2
[[1 6]
 [8 3]]
[[7 4]
 [3 4]
 [6 3]]


In [ ]:
#zero matrix

z=np.zeros([3,3,3],dtype=complex)

z

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
#one matrix
z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#matrix addition
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[3,5],[6,4]])
print(a+b)
print(a-b)


[[4 7]
 [9 8]]
[[-2 -3]
 [-3  0]]


In [ ]:
#multiplication
print(a@b)
print(a.dot(b))

[[15 13]
 [33 31]]
[[15 13]
 [33 31]]


In [ ]:
#full matrix

z=np.full([3,3],5,dtype=int)
z

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#matrix divison
print(a/b)

[[0.33333333 0.4       ]
 [0.5        1.        ]]


In [ ]:
#create a 3x4 matrix with value 9 and datatype complex

a=np.full([3,4],9,dtype=complex)
a

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#identity matrix

a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create a 4x4 matrix
y=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2]])
print(y)
print(y.size)
b=y.reshape(8,2)
print(b)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [5 4 3 2]]
16
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 8]
 [7 6]
 [5 4]
 [3 2]]


In [ ]:
#arange

a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
#create a 5x2 matrix using arange

a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3x3 matrix
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)

a.max()
a.max(axis=0)
a.max(axis=1)

a.min()
a.min(axis=0)
a.min(axis=1)

a.sum()
a.sum(axis=0)
a.sum(axis=1)
np.sqrt(a)

np.sin(a)

np.tan(a)

a.flatten()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#sort
#create a 3x3 matrix

a=np.array([[3,4,1],[5,3,1],[6,9,8]])
print(a)

#b=np.sort(a,axis=0)
#print(b)

c=np.sort(a,axis=1)
print(c)

d=np.argsort(a,axis=1)
d

a.flatten()

[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[1 3 4]
 [1 3 5]
 [6 8 9]]


array([3, 4, 1, 5, 3, 1, 6, 9, 8])